
haproxy:
  build: ./haproxy
  links:
    - server-yoko
  ports:
   - "3000:80"

server-yoko:
  build: ./server
  links:
    - redis
  expose:
    - "3000"
  environment:
    - NAME=Yoko

redis:
  image: redis:alpine
  expose:
    - "6379"
